class Handler:
    """Opaque type representing the C Handler structure."""


def alloc_something() -> Handler | None: ...
def set_something(handler: Handler, value: int) -> None: ...
def get_something(handler: Handler) -> int: ...
def free_something(handler: Handler) -> None: ...
